// <auto-generated />
using System;
using ComputerManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516232644_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("ComputerManager.API.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "To jest GPU",
                            Name = "GjePeUu"
                        },
                        new
                        {
                            Code = "CPU9999999",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "To jest CPU",
                            Name = "Super Duper Processor"
                        },
                        new
                        {
                            Code = "RAM1234567",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "To jest RAM",
                            Name = "Osiem Bajtow"
                        });
                });

            modelBuilder.Entity("ComputerManager.API.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AMD",
                            FoundationDate = new DateOnly(1969, 5, 1),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NV",
                            FoundationDate = new DateOnly(1993, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "COR",
                            FoundationDate = new DateOnly(1994, 1, 1),
                            FullName = "Corsair Gaming Inc."
                        });
                });

            modelBuilder.Entity("ComputerManager.API.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        });
                });

            modelBuilder.Entity("ComputerManager.API.Entities.Pc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warranty")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pcs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Komputer1",
                            Stock = 1,
                            Warranty = 5,
                            Weight = 50f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1999, 2, 12, 7, 3, 12, 0, DateTimeKind.Unspecified),
                            Name = "Stary Komputer",
                            Stock = 12,
                            Warranty = 1,
                            Weight = 700f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2014, 8, 12, 17, 32, 45, 0, DateTimeKind.Unspecified),
                            Name = "Nowy Komputer",
                            Stock = 5,
                            Warranty = 20,
                            Weight = 900f
                        });
                });

            modelBuilder.Entity("ComputerManager.API.Entities.PcComponent", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PcId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PcComponents");

                    b.HasData(
                        new
                        {
                            PcId = 3,
                            ComponentCode = "RAM1234567",
                            Amount = 30
                        },
                        new
                        {
                            PcId = 2,
                            ComponentCode = "CPU9999999",
                            Amount = 20
                        },
                        new
                        {
                            PcId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 10
                        });
                });

            modelBuilder.Entity("ComputerManager.API.Entities.Component", b =>
                {
                    b.HasOne("ComputerManager.API.Entities.ComponentManufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerManager.API.Entities.ComponentType", "Type")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ComputerManager.API.Entities.PcComponent", b =>
                {
                    b.HasOne("ComputerManager.API.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerManager.API.Entities.Pc", "Pc")
                        .WithMany("Components")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("ComputerManager.API.Entities.Pc", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
